language: php

php:
  - 7.3
  - 7.4
  - 8.0

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer
    - vendor

git:
  depth: 1

before_install:
  - phpenv config-rm xdebug.ini

install:
  - 'cp -f config/parameters.yml.dist config/parameters.yml'
  - composer install -n --no-progress --prefer-dist

script:
  - bin/phpunit
  - bin/phpstan analyse
