version: '2'
services:
  satisfy:
    container_name: satisfy
    build: ./docker
    volumes:
      - .:/var/www/satisfy
    environment:
      APP_PATH: /var/www/satisfy
      APP_ENV: dev
      APP_DEBUG: 0
    ports:
      - "80:80"
